var GAME_LEVELS = [
  ["                                                                             x  ",
   "                                                               xxxxx         x  ",
   "                                 xxx                          x!!!!!x        x  ",
   "                                 x!x                          xx!!!xx        x  ",
   "                               xx!!!xx                       xx!!!!!x        x  ",
   "                                x!!!x                         xx!!!x         x  ",
   "                                 xvx                            xvx        o x  ",
   "                                                                             x  ",
   "                                                                         xxxxx  ",
   "                                                                          || x  ",
   "                                                                             x  ",
   "                                                                   b         x  ",
   "  xx                                                                     |  |x  ",
   "  x                  xxxx   y                                      xx   xxxxxx  ",
   "  x                         xxxx                                       !!!!!!x  ",
   "  x          xxxxxxx           x    xxx                      xxxx     !!!!!!xx  ",
   "  x  @     y x     x!!!!!!!!!!!x    x yyyy                  y    x!!!!!!!xxxxx  ",
   "  xxxxxxxxxxxx     xxxxxxxxxxxxx    xxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxx  ",
   "                               x    x        xx     y  xxxx                     ",
   "                               x!!!!x        xx  xxxx   x                       ",
   "                               x!!!!x        x!!!!!!!!!!x                       ",
   "                               xxxxxx        xxxxxxxxxxxx                       ",
   "                                                                                ",
   "                                                                                "],
  ["                    xxxxx                                                                                             x  ",
   "                    x!!!x                  xxx                         xxxxx                                          x  ",
   "                 xxxxx!x                  x!!!x                        x!!!x                                          x  ",
   "                 x!!!xvx                   x!x                          x!x                                           x  ",
   "                  x!x                      x!x                          xvx                                         o x  ",
   "                  xvx                       v                                                                         x  ",
   "                                                                                          b                 xxxxxxxxxxx  ",
   "                                                                                                      y                  ",
   "                                                           y                                  y     xxx                  ",
   "                                                      xxxxxx                             y  xxx                          ",
   "                                                     x    x!!                          xxx                               ",
   "                                                 yxxxx    x!!                         x                                  ",
   "                                      xxxxx   xxxx        x!!                        x                                   ",
   "                               x  =  x    x!!!x           x!!    y      xxx         x                                    ",
   " x                           xxxxxxxxx    x!!!x           x!!xxxx xxxxx!!!!!x  =   x                                     ",
   " x                         yxx            xxxxx           xxxx        x!!!!!xxxxxxxx                                     ",
   " x                       xxx                                          xxxxxxx                                            ",
   " x                      xx                                                                                               ",
   " x                     xx                                                                                                ",
   " x                    xx                                                                                                 ",
   " x                   xx                                                                                                  ",
   " x                  xx                                                                                                   ",
   " x                 xx                                                                                                    ",
   " x          xxxx   x                                                                                                     ",
   " x  @         =x!!!x                                                                                                     ",
   " xxxxxxxxxxxxxxx!!!x                                                                                                     ",
   "               xxxxx                                                                                                     ",
   "                                                                                                                         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["x                  xxx     xxx                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "x                  x!x     x!x                                                                              x ",
   "x                  x!x    xx!xx                                                                           o x ",
   "x                   v      xvx                          b             x            x           x            x ",
   "x                                                                     x            x          =x        xxxxx ",
   "x                                                    xxxxxxx         =x            x           x            x ",
   "x                                                          x          x           =x           x         =  x ",
   "x                                            xxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "x                                                                                                             ",
   "x                                     xxx                                                                     ",
   "x                                                                                                             ",
   "x                              xxx                           |                                                ",
   "x                      xxx                           y      xxxx                                              ",
   "x                                                    xxx             xx                                       ",
   "x               xxx                                                                                           ",
   "x                                      x    =   x                                                             ",
   "x                    x        =    x   xxxxxxxxxx            x          = x                                   ",
   "x                    xxxxxxxxxxxxxxx        |               xxxxxxxxxxxxxxx                                   ",
   "x                          y     y                        yx                                                  ",
   "x                                                      xxxxx                                                  ",
   "x                                        |     |                                                              ",
   "x                       y     y       xxxxxxxxxxxxxxx                                                         ",
   "x                    xxxxxxxxxxxxxxxxxx                                                                       ",
   "x                                                                                                             ",
   "x                 xx                                                                                          ",
   "x                                                                                                             ",
   "x           xx                                                                                                ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x                xx                                                                                           ",
   "x                                                                                                             ",
   "x                                                                                                             ",
   "x            =xx                                                                                              ",
   "x  @         x                                                                                                ",
   "xxxxxxxxxxxxxx                                                                                                ",
   "                                                                                                              ",  
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  [" x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                                                                         x   ",
   " x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                                                                         x  ",
   " x                                                    h                         h                          x  ",
   " x      h   h             h             h             h                        hhh                         x  ",
   " x       h h               h           h              h                      hhhhhhh                       x  ",
   " x        h  hhhhh h   h    h    h    h  hhhhh hhhhh  h                    hhhhhhhhhhh                     x  ",
   " x        h  h   h h   h     h  h h  h   h   h h   h                     hhhhhhhhhhhhhhh                   x  ",
   " x        h  hhhhh hhhhh      hh   hh    hhhhh h   h  h                hhhhhhhhhhhhhhhhhhh                 x  ",
   " x    b                                                              hhhhhhhhhhhhhhhhhhhhhhh               x  ",
   " x  @                                                              hhhhhhhhhhhhhhhhhhhhhhhhhhh             x  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
